### ISSUE TITLE
Support for Label.FormattedText

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/quicktest#2]
Currently QuickTest doesn't find FormattedText of a Label. The logging output is just blank.

It would be helpful if it would match `label.FormattedText.ToString()`, which is the concatenation of all spans of the FormattedString.

**Comment by falkoschindler** [comment]
A workaround is to set `label.AutomationId = label.FormattedText.ToString();`.
Then QuickTest can Find and Tap the label as expected.

**Comment by rodja** [comment]
Available in 1.0.11.
